// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilhvxwmuekvwrekwdgyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsaHZ4d211ZWt2d3Jla3dkZ3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODEyMDYsImV4cCI6MjA1ODE1NzIwNn0.w7cH3o9MwpWZ97EjuVh8D-HqM1ESq26fvb-2SWQtmoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);